### PR TITLE
A11y body text link styling

### PR DESCRIPTION
**Pull request by neilblair**
Adds a 
- new mixin (see https://github.com/dof-dss/nicsdru_nidirect_theme/pull/178/files#diff-8249c32f75609390d05cdb61b55a930d3a3efcb356c580db21885de638bb8294) called "link-state-style"
- a number of maps mapping out link styles for various types of links (defined in _variables.scss)
- updates various partials containing link styles to use the new mixin.  

Essentially the idea of mapping state styles for links is that for each entry in the map is a link property that changes with state (color, background-color, outline-color, etc) - you then specify the value for different links states in a child map for that property - e.g. here is the $link-base map:

```
$link-base: (
  // Base styling for all links.
  // Maps for specific types of links may want/need to override styles configured here.
  color: (
    default: $link,
    visited: $link-visited,
    focus: #fff,
    hover: $link,
    action: $link-active
  ),
  background-color: (
    default: transparent,
    focus: $link,
  ),
  text-decoration: none,
  border-bottom: (
    default: '1px solid #{$link}',
    visited: inherit,
    focus: inherit,
    hover: '2px solid #{color(headings)}',
    active: '2px solid #{$link-active}'
  ),
  box-shadow: (
    default: none,
    focus: '0 0 0 3px #{$link}',
  ),
  outline: 0
);
```

The main reason for mapping out link state styles in this way is to gather together all the link state styles used
across the site in a single place. This hopefully makes it easier to overview and configure links styles to comply with
design requirements and with WCAG colour contrast and state indicator requirements.

### CODE REVIEW

**Review by omahm — APPROVED** [review]
Nice one 👍

**Review by DuttonMa — APPROVED** [review]
Looks really good

**Review by David-Corbett — APPROVED** [review]
hard to wrap ones head around this, but I suspect that works ok

**Comment by neilblair** [comment]
Gimme a shout @David-Corbett if you want me to go through this - its maybe not the best way to achieve this - although any SASS mixins I could find for setting link colours were incredibly basic only allowing you to set colors (and not things like text-decoration and outlines) or they were incredibly complex and introduced new problems.  (There was one, for example, which auto adjusted colors to meet WCAG colour contrast requirements - which sometimes would mean colours don't look quite right ...).

This mixin allows you to set any properties for links you want.  And it tries to resolve 3 problems:

1) When trying to get all your link styles sorted out for accessibility, you have to go all over the place to find them.  Mapping them in one place sorts this.

2) You run into all sorts of issues applying changes - especially if you make changes to base styles that get inherited by all the other styles (which are all over the place) - or if you mistakenly get order of defining states wrong, etc.  The mixin and the maps help to sort this.  The mixin outputs rules in the correct order.  And any defaults for a property you supply in the map will be explicitly applied to all states to ward off inheritance issues.

3) It is difficult to compare how specific properties (like color) vary across all states at a glance and you often need to resort to using browser inspector tools to see what a link does in different states.  The mapping helps here - especially since it kind turns things on their head in relation to how you normally specify state changes.   

Normally in CSS you specify all the properties for :visited and then all the properties for :focus, etc.  It can be hard to spot how a single property varies across states.  In the maps, things are flipped because you specify all the state variations for a property (rather than all properties for a state!).  So it is easier, I find, to see how a single property varies across changes in state ...

**Pull request merged**
